# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
